/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.senai.sc.view;

import br.senai.sc.controller.VagaController;
import br.senai.sc.model.Vaga;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadastroVagaUI extends javax.swing.JInternalFrame {

    private Vaga vagaAlteracao;
    private ArrayList<Vaga> listaVaga;
   
    public CadastroVagaUI(Vaga vaga) {
        initComponents();
        
        
        
        
    }
     public void atualizarTabelaVagas(){
        DefaultTableModel modeloVaga = new DefaultTableModel();
        modeloVaga.setColumnIdentifiers(new String[] {"Vaga","Tipo Vaga","Tipo Valor","Valor R$"});
        this.listaVaga = VagaController.obterInstancia().listarTodos();
        for ( int i=0; i < this.listaVaga.size(); i++){
            modeloVaga.addRow(new Object[] { 
                this.listaVaga.get(i).getNumeroVaga(),
                this.listaVaga.get(i).getTipoVaga(),
                this.listaVaga.get(i).getTipoValor(),
                this.listaVaga.get(i).getValorUnit()});
        }
        jtVagaCadastroVaga.setModel(modeloVaga);        
    
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlVagaCadastroVaga = new javax.swing.JLabel();
        jlTipoCadastroVaga = new javax.swing.JLabel();
        jtfVagaCadastroVaga = new javax.swing.JTextField();
        jcbTipoCadastroVaga = new javax.swing.JComboBox();
        jlValorCadastroVaga = new javax.swing.JLabel();
        jtfValorCadastroVaga = new javax.swing.JTextField();
        jlTipoValorCadastroVaga = new javax.swing.JLabel();
        jpVagaCadastroVaga = new javax.swing.JPanel();
        jbAlterarCadastroVagas = new javax.swing.JButton();
        jbDeletarCadastroVaga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVagaCadastroVaga = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jcbTipoValor = new javax.swing.JComboBox();
        jbSalvarCadastroVaga = new javax.swing.JButton();
        jbListaVagas = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro de Vagas");
        setMinimumSize(new java.awt.Dimension(404, 228));
        setOpaque(false);

        jlVagaCadastroVaga.setText("Vaga:");

        jlTipoCadastroVaga.setText("Tipo:");

        jcbTipoCadastroVaga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avulso", "Mensalista" }));

        jlValorCadastroVaga.setText("Valor unit. R$:");

        jlTipoValorCadastroVaga.setText("Tipo valor:");

        jpVagaCadastroVaga.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Vagas:")));

        jbAlterarCadastroVagas.setText("Alterar");
        jbAlterarCadastroVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarCadastroVagasActionPerformed(evt);
            }
        });

        jbDeletarCadastroVaga.setText("Deletar");
        jbDeletarCadastroVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarCadastroVagaActionPerformed(evt);
            }
        });

        jtVagaCadastroVaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaga", "Tipo Vaga", "Tipo Valor", "Valor R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVagaCadastroVaga);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jpVagaCadastroVagaLayout = new javax.swing.GroupLayout(jpVagaCadastroVaga);
        jpVagaCadastroVaga.setLayout(jpVagaCadastroVagaLayout);
        jpVagaCadastroVagaLayout.setHorizontalGroup(
            jpVagaCadastroVagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVagaCadastroVagaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jbAlterarCadastroVagas)
                .addGap(40, 40, 40)
                .addComponent(jbDeletarCadastroVaga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVagaCadastroVagaLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jpVagaCadastroVagaLayout.setVerticalGroup(
            jpVagaCadastroVagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVagaCadastroVagaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpVagaCadastroVagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarCadastroVagas)
                    .addComponent(jbDeletarCadastroVaga)
                    .addComponent(jButton1))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jcbTipoValor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mensal", "Hora/Fração" }));

        jbSalvarCadastroVaga.setText("Salvar");
        jbSalvarCadastroVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarCadastroVagaActionPerformed(evt);
            }
        });

        jbListaVagas.setText("Listar");
        jbListaVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaVagasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlVagaCadastroVaga)
                                    .addComponent(jlTipoCadastroVaga)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlValorCadastroVaga))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jlTipoValorCadastroVaga)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jbSalvarCadastroVaga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbListaVagas))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfVagaCadastroVaga, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jcbTipoCadastroVaga, 0, 119, Short.MAX_VALUE)
                                .addComponent(jtfValorCadastroVaga, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jcbTipoValor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jpVagaCadastroVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlVagaCadastroVaga)
                    .addComponent(jtfVagaCadastroVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlTipoCadastroVaga))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jcbTipoCadastroVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTipoValorCadastroVaga)
                    .addComponent(jcbTipoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValorCadastroVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValorCadastroVaga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarCadastroVaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbListaVagas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpVagaCadastroVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarCadastroVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarCadastroVagaActionPerformed
   
         try {
            if ( vagaAlteracao != null ) {
                vagaAlteracao.setNumeroVaga(Integer.parseInt(jtfVagaCadastroVaga.getText().trim()));
                vagaAlteracao.setTipoVaga(jcbTipoCadastroVaga.getSelectedItem().toString());
                vagaAlteracao.setTipovalor(jcbTipoValor.getSelectedItem().toString());
                vagaAlteracao.setValorUnit(new Double(jtfValorCadastroVaga.getText()).doubleValue());
                VagaController.obterInstancia().alterar(vagaAlteracao);
                JOptionPane.showMessageDialog(null, "Vaga alterada com sucesso");
            } else {
                Vaga vaga = new Vaga();
                vaga.setNumeroVaga(Integer.parseInt(jtfVagaCadastroVaga.getText().trim()));
                vaga.setTipoVaga(jcbTipoCadastroVaga.getSelectedItem().toString());
                vaga.setTipovalor(jcbTipoValor.getSelectedItem().toString());
                vaga.setValorUnit(new Double(jtfValorCadastroVaga.getText()).doubleValue());
                VagaController.obterInstancia().inserir(vaga);
                atualizarTabelaVagas();
                JOptionPane.showMessageDialog(null, "Vaga cadastrada com sucesso");
                
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() );

        }
    }//GEN-LAST:event_jbSalvarCadastroVagaActionPerformed

    private void jbListaVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaVagasActionPerformed
      atualizarTabelaVagas();
    }//GEN-LAST:event_jbListaVagasActionPerformed

    private void jbAlterarCadastroVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarCadastroVagasActionPerformed
        
        try{ 
            for ( int i=0; i < this.listaVaga.size(); i++ ){
                if ( jtVagaCadastroVaga.getSelectedRow() == i ){
                    vagaAlteracao = new Vaga();
                    vagaAlteracao.setNumeroVaga(this.listaVaga.get(i).getNumeroVaga());
                    vagaAlteracao.setId(this.listaVaga.get(i).getId());
                    vagaAlteracao.setTipoVaga(this.listaVaga.get(i).getTipoVaga());
                    vagaAlteracao.setTipovalor(this.listaVaga.get(i).getTipoValor());
                    vagaAlteracao.setValorUnit(this.listaVaga.get(i).getValorUnit());
                    jtfVagaCadastroVaga.setText(new Integer(this.listaVaga.get(i).getNumeroVaga()).toString());
                    jcbTipoCadastroVaga.setSelectedItem(this.listaVaga.get(i).getTipoVaga());
                    jcbTipoValor.setSelectedItem(this.listaVaga.get(i).getTipoValor());
                    jtfValorCadastroVaga.setText(new Double (this.listaVaga.get(i).getValorUnit()).toString());
                    
                   
                    
                }
            }
       } catch ( Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
       }
       atualizarTabelaVagas();
                                                    
                                                         
        
    
    }//GEN-LAST:event_jbAlterarCadastroVagasActionPerformed

    private void jbDeletarCadastroVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarCadastroVagaActionPerformed
     
          try {
          
            this.listaVaga = VagaController.obterInstancia().listarTodos();
            VagaController.obterInstancia().
                    remover(this.listaVaga.get(jtVagaCadastroVaga.getSelectedRow()));
            
        } catch ( ArrayIndexOutOfBoundsException a){
            JOptionPane.showMessageDialog(null, "Selecione uma vaga");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
        atualizarTabelaVagas();
                                                
                                           
        
        
    }//GEN-LAST:event_jbDeletarCadastroVagaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterarCadastroVagas;
    private javax.swing.JButton jbDeletarCadastroVaga;
    private javax.swing.JButton jbListaVagas;
    private javax.swing.JButton jbSalvarCadastroVaga;
    private javax.swing.JComboBox jcbTipoCadastroVaga;
    private javax.swing.JComboBox jcbTipoValor;
    private javax.swing.JLabel jlTipoCadastroVaga;
    private javax.swing.JLabel jlTipoValorCadastroVaga;
    private javax.swing.JLabel jlVagaCadastroVaga;
    private javax.swing.JLabel jlValorCadastroVaga;
    private javax.swing.JPanel jpVagaCadastroVaga;
    private javax.swing.JTable jtVagaCadastroVaga;
    private javax.swing.JTextField jtfVagaCadastroVaga;
    private javax.swing.JTextField jtfValorCadastroVaga;
    // End of variables declaration//GEN-END:variables
}