/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.view;

import br.senai.sc.controller.ClienteController;
import br.senai.sc.controller.VagaController;
import br.senai.sc.model.Cliente;
import br.senai.sc.model.Vaga;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class ConsultaVagaUI extends javax.swing.JInternalFrame {

    private ArrayList<Vaga> listaVaga;

    /**
     * Creates new form ConsultaVagaUI
     */
    public ConsultaVagaUI(Vaga vaga) {
        initComponents();
    }

    public void atualizarTabelaVaga() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Vaga", "Tipo", "Status"});
        this.listaVaga = VagaController.obterInstancia().listarTodos();
        for (int i = 0; i < this.listaVaga.size(); i++) {
            String status = null;

            if (this.listaVaga.get(i).getStatus() == 0) {
                status = "Disponível";

            } else {
                status = "Ocupado";
            }
            modelo.addRow(new Object[]{
                this.listaVaga.get(i).getNumeroVaga(),
                this.listaVaga.get(i).getTipoVaga(),
                status});




        }
        jtConsultaVaga.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPesquisarVagaConsultaVaga = new javax.swing.JPanel();
        jspConsultaVaga = new javax.swing.JScrollPane();
        jtConsultaVaga = new javax.swing.JTable();
        jbConsultarConsultaVaga = new javax.swing.JButton();
        jbSairConsultaVaga = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pesquisa de Vagas Disponíveis");

        jpPesquisarVagaConsultaVaga.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Vagas"));

        jtConsultaVaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vagas", "Tipo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspConsultaVaga.setViewportView(jtConsultaVaga);

        jbConsultarConsultaVaga.setText("Consultar");
        jbConsultarConsultaVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarConsultaVagaActionPerformed(evt);
            }
        });

        jbSairConsultaVaga.setText("Sair");
        jbSairConsultaVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairConsultaVagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPesquisarVagaConsultaVagaLayout = new javax.swing.GroupLayout(jpPesquisarVagaConsultaVaga);
        jpPesquisarVagaConsultaVaga.setLayout(jpPesquisarVagaConsultaVagaLayout);
        jpPesquisarVagaConsultaVagaLayout.setHorizontalGroup(
            jpPesquisarVagaConsultaVagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisarVagaConsultaVagaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbConsultarConsultaVaga)
                .addGap(18, 18, 18)
                .addComponent(jbSairConsultaVaga)
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPesquisarVagaConsultaVagaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspConsultaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPesquisarVagaConsultaVagaLayout.setVerticalGroup(
            jpPesquisarVagaConsultaVagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisarVagaConsultaVagaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspConsultaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPesquisarVagaConsultaVagaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultarConsultaVaga)
                    .addComponent(jbSairConsultaVaga))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPesquisarVagaConsultaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPesquisarVagaConsultaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairConsultaVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairConsultaVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairConsultaVagaActionPerformed

    private void jbConsultarConsultaVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarConsultaVagaActionPerformed
        // TODO add your handling code here:
        atualizarTabelaVaga();
    }//GEN-LAST:event_jbConsultarConsultaVagaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConsultarConsultaVaga;
    private javax.swing.JButton jbSairConsultaVaga;
    private javax.swing.JPanel jpPesquisarVagaConsultaVaga;
    private javax.swing.JScrollPane jspConsultaVaga;
    private javax.swing.JTable jtConsultaVaga;
    // End of variables declaration//GEN-END:variables
}
