/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.view;

import br.senai.sc.model.Vaga;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import javax.security.auth.Refreshable;
import javax.swing.JDesktopPane;

/**
 *
 * @author Caio Pereira
 */
public class PrincipalUI extends javax.swing.JFrame {
    
    private static PrincipalUI instanciaRep;
    private JDesktopPane desk;
    
    

public static PrincipalUI obterInstancia(){
        if ( instanciaRep == null ) {
            instanciaRep = new PrincipalUI();
        }
        return instanciaRep;
    }
    //private PopupMenu registroMovimentacaoUI;

public static  JDesktopPane getPainelPrincipal() {
    return obterInstancia().jdpPrincipal;
}

    public PrincipalUI(JDesktopPane jdpPrincipal) {
        this.jdpPrincipal = jdpPrincipal;
    }

    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
         setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jBCadastroVaga = new javax.swing.JButton();
        jBCadastroMensalista = new javax.swing.JButton();
        jBMovimentacao = new javax.swing.JButton();
        jBConsultaVaga = new javax.swing.JButton();
        jBRelatorioFaturamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setMinimumSize(new java.awt.Dimension(1024, 768));

        jBCadastroVaga.setText("Cadastro Vaga");
        jBCadastroVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroVagaActionPerformed(evt);
            }
        });
        jBCadastroVaga.setBounds(20, 100, 150, 30);
        jdpPrincipal.add(jBCadastroVaga, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBCadastroMensalista.setText("Cadastro Cliente");
        jBCadastroMensalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroMensalistaActionPerformed(evt);
            }
        });
        jBCadastroMensalista.setBounds(20, 50, 150, 30);
        jdpPrincipal.add(jBCadastroMensalista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBMovimentacao.setText("Movimentação");
        jBMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMovimentacaoActionPerformed(evt);
            }
        });
        jBMovimentacao.setBounds(20, 150, 150, 30);
        jdpPrincipal.add(jBMovimentacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBConsultaVaga.setText("Consulta Vaga");
        jBConsultaVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaVagaActionPerformed(evt);
            }
        });
        jBConsultaVaga.setBounds(220, 100, 150, 30);
        jdpPrincipal.add(jBConsultaVaga, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBRelatorioFaturamento.setText("Relatório Faturamento");
        jBRelatorioFaturamento.setToolTipText("");
        jBRelatorioFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioFaturamentoActionPerformed(evt);
            }
        });
        jBRelatorioFaturamento.setBounds(220, 150, 150, 30);
        jdpPrincipal.add(jBRelatorioFaturamento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastroVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroVagaActionPerformed
        CadastroVagaUI cadastroVagaUI = new CadastroVagaUI(null);
        jdpPrincipal.add(cadastroVagaUI);
        cadastroVagaUI.setVisible(true);
    }//GEN-LAST:event_jBCadastroVagaActionPerformed

    private void jBCadastroMensalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroMensalistaActionPerformed
        CadastroClienteUI cadastroClienteUI = new CadastroClienteUI(null);
        jdpPrincipal.add(cadastroClienteUI);
        cadastroClienteUI.setVisible(true);
       // PrincipalUI.abrirCadastroCLiente();
    }//GEN-LAST:event_jBCadastroMensalistaActionPerformed

   // public static void abrirCadastroCLiente(){
     //   CadastroClienteUI cadastroClienteUI = new CadastroClienteUI(null);
      //  jdpPrincipal.add(cadastroClienteUI);
      //  cadastroClienteUI.setVisible(true);        
        
    
    private void jBMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMovimentacaoActionPerformed
        RegistroMovimentacaoUI registroMovimentacaoUI = new RegistroMovimentacaoUI();
        jdpPrincipal.add(registroMovimentacaoUI);
        registroMovimentacaoUI.setVisible(true);
    }//GEN-LAST:event_jBMovimentacaoActionPerformed

    private void jBConsultaVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaVagaActionPerformed
        ConsultaVagaUI consultaVagaUI = new ConsultaVagaUI(null);
        jdpPrincipal.add(consultaVagaUI);
        consultaVagaUI.setVisible(true);
        
    }//GEN-LAST:event_jBConsultaVagaActionPerformed

    private void jBRelatorioFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioFaturamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRelatorioFaturamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                obterInstancia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastroMensalista;
    private javax.swing.JButton jBCadastroVaga;
    private javax.swing.JButton jBConsultaVaga;
    private javax.swing.JButton jBMovimentacao;
    private javax.swing.JButton jBRelatorioFaturamento;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.gif")));
    }
}
