/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.view;

import br.senai.sc.controller.ClienteController;
import br.senai.sc.model.Cliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caio Pereira
 */
public class ConsultaClienteUI extends javax.swing.JInternalFrame {
    
  private ArrayList<Cliente> listaCliente;

  
    public ConsultaClienteUI() {
        initComponents();
    }
    
    public void atualizarTabelaClientes(){
        DefaultTableModel modeloClientes = new DefaultTableModel();
        modeloClientes.setColumnIdentifiers(new String[] {"CARTÃO","CLIENTE","CPF","PLACA","MODELO"});
        this.listaCliente = ClienteController.obterInstancia().listarTodos();
        for ( int i=0; i < this.listaCliente.size(); i++){
            modeloClientes.addRow(new Object[] { 
                this.listaCliente.get(i).getCartaoPark(), 
                this.listaCliente.get(i).getNome(), 
                this.listaCliente.get(i).getCpf(), 
                this.listaCliente.get(i).getPlaca(), 
                this.listaCliente.get(i).getModelo()});
        }
        jtConsultaClientes.setModel(modeloClientes);
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConsultaCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultaClientes = new javax.swing.JTable();
        jbListarCliente = new javax.swing.JButton();

        jpConsultaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        jtConsultaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cartão", "Cliente", "CPF", "Placa", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(jtConsultaClientes);

        jbListarCliente.setText("listar");
        jbListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaClienteLayout = new javax.swing.GroupLayout(jpConsultaCliente);
        jpConsultaCliente.setLayout(jpConsultaClienteLayout);
        jpConsultaClienteLayout.setHorizontalGroup(
            jpConsultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaClienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpConsultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbListarCliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpConsultaClienteLayout.setVerticalGroup(
            jpConsultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbListarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jpConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarClienteActionPerformed
        atualizarTabelaClientes();
    }//GEN-LAST:event_jbListarClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbListarCliente;
    private javax.swing.JPanel jpConsultaCliente;
    private javax.swing.JTable jtConsultaClientes;
    // End of variables declaration//GEN-END:variables
}
